
import React from 'react';
import {
  StyleSheet
} from 'react-native';
import {redish, blueish, yellowish, lightGrey, darkGrey, tempLoginViewRedish} from './Components/Constants'

const styles = StyleSheet.create({
  containerLogin: {
   flex: 1,
   justifyContent: 'center',
   alignItems: 'center',
   backgroundColor: tempLoginViewRedish,
  },
  loginTopSpacer: {
    position: 'relative',
    top: 35
  },
  loginTitlePhantom: {
    fontFamily: 'BudmoJiggler-Regular',
    fontSize: 70,
    backgroundColor: 'transparent',
    textAlign: 'center',
    top: -25
  },
  loginTitleRacer : {
    fontFamily: 'Airstream',
    fontSize: 120,
    textAlign: 'center',
    color: blueish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
    top: -70,
    textAlign: 'right',
    marginRight: 10
  },
  loginCenterer: {
    alignItems: 'center'
  },
  loginTopSpacer2: {
    position: 'relative',
    top: -30
  },
  loginTopSpacer3: {
    alignItems: 'center',
    position: 'relative',
    top: -50
  },
  loginInputLabel: {
    fontFamily: 'Magnum',
    fontSize: 30,
    fontWeight: '900',
    color: yellowish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3, marginTop: 10
  },
  loginBtnText: {
    fontFamily: 'Magnum',
    fontSize: 40,
    textAlign: 'center',
    color: yellowish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    textAlign: 'right',
    marginRight: 5,
    marginTop: 10,
    position: 'relative',
    top: 10
  },
  loginBtnView: {
    height: 50,
    width: 200,
    backgroundColor: blueish,
    zIndex: -1,
    borderRadius: 100,
    position: 'relative',
    top: -35,
    borderColor: yellowish,
    borderWidth: 3
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: redish,
  },
  container2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  statsHeader: {
    width: 375,
    height: 60,
    backgroundColor: 'transparent',
    alignItems: 'center',
    zIndex: 0
  },
  statsUsername: {
    color: 'black',
    fontFamily: 'budmo',
    fontSize: 60,
    backgroundColor: 'transparent',
    zIndex: 3,
    paddingTop: 10
  },
  statsUserLocation: {
    fontFamily: 'Magnum',
    fontSize: 65,
    color: blueish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
    top: 10,
    left: -70,
    zIndex: 3
  },
  statsStatsHeadingWrapper: {
    flex: 1,
    backgroundColor: 'black'
  },
  statsStatsHeadingBox: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 5
  },
  statsTime: {
    fontFamily: 'Ghoulish Intent',
    fontSize: 25,
    textAlign: 'right',
    color: yellowish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3
  },
  runPopupFrame: {
    position: 'absolute',
    top: 410
  },
  runPopupOverImage: {
    width: 375,
    height: 156,
    backgroundColor: 'transparent',
    borderColor: 'black',
    borderWidth: 10,
    position: 'relative',
    top: -156
  },
  runPopupTextTop: {
    fontFamily: 'BudmoJiggler-Regular',
    fontSize: 45,
    backgroundColor: 'transparent',
    textAlign: 'center',
    bottom: 290
  },
  runPopupTextBottom: {
    fontFamily: 'Magnum',
    fontSize: 50,
    textAlign: 'center',
    color: blueish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
    bottom: 260,
    marginRight: 10
  },
  runPopupTextTop2: {
    fontFamily: 'BudmoJiggler-Regular',
    fontSize: 45,
    backgroundColor: 'transparent',
    textAlign: 'center',
    bottom: 290
  },
  runPopupTextBottom2Wrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  runPopupFlexRow: {
    flexDirection: 'row'
  },
  runPopupTextBottom2: {
    fontFamily: 'Magnum',
    fontSize: 50,
    textAlign: 'center',
    color: blueish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
    bottom: 270,
    marginRight: 10
  },
  runPopupInput: {
    height: 45,
    width: 65,
    backgroundColor: 'black',
    position: 'relative',
    bottom: 270,
    borderRadius: 20,
    borderWidth: 5,
    borderColor: blueish,
    textAlign: 'center',
    fontFamily: 'Magnum',
    fontSize: 28,
    color: yellowish,
    paddingTop: 5
  },
  opponentHeader: {
    width: 375,
    height: 60,
    backgroundColor: 'transparent',
    alignItems: 'center',
    zIndex: 0
  },
  opponentHeaderTextTop: {
    color: 'black',
    fontFamily: 'budmo',
    fontSize: 50,
    backgroundColor: 'transparent',
    zIndex: 3,
    paddingTop: 5
  },
  opponentHeaderTextBottom: {
    fontFamily: 'Magnum',
    fontSize: 75,
    color: blueish,
    backgroundColor: 'transparent',
    position: 'relative',
    top: 20,
    left: -20,
    zIndex: 3,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3
  },
  opponentListWrapper: {
    flex: 1,
    padding: 3,
    backgroundColor: 'black',
    position: 'relative'
  },
  opponentListRow: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 5
  },
  runARoutePopupWrapper: {
    position: 'absolute',
    top: 400
  },
  runARoutePopupFrame: {
    width: 375,
    height: 211,
    backgroundColor: 'transparent',
    borderColor: 'black',
    borderWidth: 10,
    position: 'relative',
    top: -209
  },
  runARoutePopupText1: {
    fontFamily: 'Magnum',
    fontSize: 70,
    backgroundColor: 'transparent',
    textAlign: 'center',
    color: yellowish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    position: 'relative',
    top: -410
  },
  runARoutePopupText2: {
    fontFamily: 'BudmoJiggler-Regular',
    fontSize: 40,
    backgroundColor: 'transparent',
    textAlign: 'center',
    top: -410
  },
  runARoutePopupText3: {
    fontFamily: 'Airstream',
    fontSize: 40,
    textAlign: 'center',
    color: yellowish,
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
    top: -410,
    marginRight: 10
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: 'black',
    marginBottom: 5,
  },
  navigationBar: {
    margin: 5,
    paddingTop: 15,
    flexDirection: 'row',
    backgroundColor: 'blue',
    position: 'absolute',
    paddingTop: 0,
    bottom: 5,
    height: 64,
    right: 0,
    left: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: 'white',
  },
  navButton: {
    color: 'white',
    textAlign: 'center',
    margin: 15,
    width: '17%',
  },
  button: {
    backgroundColor: 'blue',
    color: 'white',
    height: 30,
    lineHeight: 30,
    marginTop: 10,
    textAlign: 'center',
    width: 250
  },
  input: {
    color: yellowish,
    fontFamily:'Ghoulish Intent',
    fontSize: 20,
    backgroundColor: 'black',
    margin: 'auto',
    padding: 10,
    textAlign: 'center',
    borderColor: 'black',
    borderWidth: 3,
    borderRadius: 18,
    height: 35,
    width: 250,
  },
  mapcontainer: {
    height: 555,
    width: 375,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    display: 'flex'
  },
  mapcontainerNoNav: {
    height: 600,
    width: 375,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    display: 'flex'
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    zIndex: 0,

  },
    icon: {
    width: 26,
    height: 26,
  },
  createRoute: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
  },
  filter: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    right: 50,
  },
  filterHolder: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 60,
    right: 50,
  },
   filterInput: {
    color: yellowish,
    fontFamily:'Ghoulish Intent',
    fontSize: 20,
    backgroundColor: 'black',
    margin: 'auto',
    padding: 10,
    textAlign: 'center',
    borderColor: 'black',
    borderWidth: 3,
    borderRadius: 18,
    height: 35,
    width: 50,
  },
  btnHolder: {
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 50,
    width: '100%',
    position: 'absolute',
    top: 20,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  btnHolderVert: {
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 50,
    width: 100,
    position: 'absolute',
    left: 25,
    top: 20,
    alignItems: 'flex-start',
    justifyContent: 'space-around'
  },
  btnHolderLow: {
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 20,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  genRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 65,
    left: 50,
  },
  incrementRouteNum: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 100,
    left: 50,
  },
  timer: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
   startStop: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    left: 50,
  },
  viewRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    top: 30,
    left: 50,
  },
  finalTime: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    left: 50,
  },
   submitRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    bottom: 30,
    left: 50,
  },
  replayRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    bottom: 30,
    right: 50,
  },
  finalDistance: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
    replaySpeed1: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
  replaySpeed2: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 80,
    right: 50,
  },
  replaySpeed4: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 130,
    right: 50,
  },
  replaySpeed10: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 180,
    right: 50,
  },
   changeView: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    top: 30,
    left: 50,
  },
  changeTypeHeartRate: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 10,
  },
  changeTypeSpeed: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 100,
  },
  changeTypeRegular: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 190,
  },
   replayRoute: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'yellow',
    position: 'absolute',
    top: 100,
    right: 10,
  },
  homeButton: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'red',
    position: 'absolute',
    bottom: 200,
    left: 200,
  },
  replayTimer: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'purple',
    position: 'absolute',
    top: 100,
    right: 100,
  },
   popUpMessage: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'purple',
    position: 'absolute',
    top: 100,
    right: 100,
  },
  userHeader: {
    display: 'flex',
    backgroundColor: 'orange',
    height: 200,
    width: 500,
    justifyContent: 'center',

  },

  userCity: {
    justifyContent: 'center'
  },
  userName: {
    alignItems: 'center'
  },
  userStats: {
    margin: 2
  },
  scrollListHeader: {
    fontFamily: 'Magnum',
    fontWeight: '900',
    width: '33%',
    height: 35,
    color: yellowish,
    textAlign: 'center',
    fontSize: 20,
    padding: 3,
    paddingTop: 7,
    backgroundColor: 'black',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish
  },
  scrollListHeader2: {
    fontFamily: 'Magnum',
    fontWeight: '900',
    width: '48%',
    height: 35,
    color: yellowish,
    textAlign: 'center',
    fontSize: 25,
    padding: 3,
    paddingTop: 7,
    backgroundColor: 'black',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish
  },
  scrollListRow: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: 15,
    backgroundColor: 'white',
  },
  scrollListRowOdd: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderWidth: 1,
    borderColor: yellowish,
  },
  scrollListRowEven: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderWidth: 1,
    borderColor: yellowish,
  },
  scrollListItem: {
    textAlign: 'center',
    fontFamily: 'Ghoulish Intent',
    fontSize: 25,
    color: yellowish,
    backgroundColor: 'transparent',
    width: '30%',
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
  },
  scrollListItem2: {
    textAlign: 'center',
    fontFamily: 'Ghoulish Intent',
    fontSize: 30,
    color: yellowish,
    backgroundColor: 'transparent',
    width: '48%'
  },
  genRouteStatus:{
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 400,
    left: 50,
  },
  setStartEnd: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 200,
    left: 50,
  },
  scrollListItemOppNameOdd: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: redish,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish,
    margin: 1,
  },
  scrollListItemOppNameEven: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: blueish,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish,
    margin: 1,
  },
  scrollListItemOppName: {
    paddingTop: 3,
    textAlign: 'center',
    fontFamily: 'Magnum',
    fontSize: 25,
    color: yellowish,
    width: '48%',
    backgroundColor: 'transparent',
    textShadowColor: 'black',
    textShadowRadius: 1,
    textShadowOffset: {width : 1, height: 1}
  },
  dot: {
     width: 10,
     height: 10,
     borderRadius: 5,
     backgroundColor: redish
   },
   dotBlack: {
     width: 10,
     height: 10,
     borderRadius: 5,
     backgroundColor: 'black'
   },
   dotGrey: {
     width: 10,
     height: 10,
     borderRadius: 5,
     backgroundColor: lightGrey
   },

  });

export default styles
